# Generated by Django 4.2.26 on 2025-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(blank=True, choices=[('ps4', 'PlayStation 4'), ('ps5', 'PlayStation 5'), ('xbox', 'Xbox'), ('universal', 'Универсальный')], help_text='Платформа для консолей и аксессуаров', max_length=20, null=True, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('essential', 'Plus Essential'), ('extra', 'Plus Extra'), ('deluxe', 'Plus Deluxe')], help_text='Тип подписки PlayStation Plus', max_length=20, null=True, verbose_name='Тип подписки'),
        ),
    ]
