# Generated by Django 4.2.26 on 2025-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_platform_product_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, help_text='Например: dualsense-ps5, ps-plus-deluxe', max_length=50, null=True, verbose_name='Группа вариантов'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Например: Белый, Чёрный, 1 месяц, 3 месяца, 12 месяцев', max_length=50, null=True, verbose_name='Название варианта'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_order',
            field=models.IntegerField(default=0, verbose_name='Порядок варианта'),
        ),
    ]
