# Generated by Django 4.2.26 on 2025-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_variant_group_product_variant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_color',
            field=models.CharField(blank=True, help_text='HEX-цвет, например: #ffffff, #000000, #1e90ff', max_length=7, null=True, verbose_name='Цвет варианта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_order',
            field=models.IntegerField(default=0, help_text='Для сортировки вариантов (0,1,2...)', verbose_name='Порядок варианта'),
        ),
    ]
