# Generated by Django 4.2.26 on 2025-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_variant_color_alter_product_variant_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved', '-date'], name='main_review_is_appr_3409f9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_approved'], name='main_review_is_appr_1a0054_idx'),
        ),
    ]
