# Generated by Django 4.2.26 on 2025-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_main_review_is_appr_3409f9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерирован'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплён'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_pinned', '-date'], name='main_review_is_pinn_eb7167_idx'),
        ),
    ]
