# Generated by Django 4.2.26 on 2026-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review_is_generated_review_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('essential', 'Plus Essential'), ('extra', 'Plus Extra'), ('deluxe', 'Plus Deluxe'), ('ea play', 'EA Play')], help_text='Тип подписки PlayStation Plus', max_length=20, null=True, verbose_name='Тип подписки'),
        ),
    ]
